### ISSUE TITLE
Brandock's XP

### ISSUE THREAD

**Issue by ChitownWillie** [Gitjas/Brandock_the_Mage#1]
Hello,

Just a few questions about Brandock's starting XP:

1. Just curious how you decided on starting value (2510).

2. Readme states:

_"When first met in BG1, he will be a first level mage"_

But 2510 should put him at Level 2.

Thanks!

**Comment by Gitjas** [comment]
Hi! Yes, that's an inconsistency between the description and the cre file. I'll adjust this; didn't make up my mind whether to change the starting level or just the readme description, though.
Thanks for the query!

**Comment by ChitownWillie** [comment]
Gotcha.

Is the idea to be on par w/ Xzar or Xan (i.e., entry-level mage w/ 2 spell
slots)?

**Comment by Gitjas** [comment]
My idea was that it makes sense story-wise that he is no longer level 1 as he is depicted as a quick and very talented learner who already studied with the Cowled Wizards (like the apprentices of the BGII mage stronghold). 
From game playing POV he shouldn't be too high levelled, though. I think I will leave him at level 2 and adjust the readme description.

**Comment by ChitownWillie** [comment]
Thanks Gitjas!

**Comment by Gitjas** [comment]
I decided to leave him at level 2 and adjust the readme for the next version.
