### ISSUE TITLE
Sling proficiency

### ISSUE THREAD

**Issue by ChitownWillie** [Gitjas/Brandock_the_Mage#5]
Noticed that he has a Sling proficiency with 0 stars - is this intended?

![image](https://user-images.githubusercontent.com/65503897/179569423-6c7d7a83-f3e5-4bdc-b4a8-726a0c3a4019.png)

**Comment by Gitjas** [comment]
I have no idea. I'll investigate. Thanks!

**Comment by Gitjas** [comment]
Will be deleted in v1.3.
