### ISSUE TITLE
Integration w/ Valerie NPC

### ISSUE THREAD

**Issue by ChitownWillie** [Gitjas/Brandock_the_Mage#6]
Hi Gitjas,

Just wondering if you had plans to integrate Brandock with Valerie.

They have very similar backgrounds:

"She was found and taken in by the Cowled Wizards, the nation's arcane police, who taught her how to use and control her abilities. Upon completing her apprenticeship, she was posted to Nashkel with the Amnish army where you met her."

Perhaps a quest where they team up and discover Cowled secrets? Just thinking out loud.

**Comment by Gitjas** [comment]
Unfortunately, the author of Valerie has disappeared. Even the crossmod banters included in Brandock aren't authorized (as stated in the mod's changelog).

**Comment by ChitownWillie** [comment]
Oh well. Still enjoying Brandock - Thanks for all your hard work!

**Comment by Gitjas** [comment]
Thanks!
